-- ============================================================
-- الأساس: القاعدة مثل ما كانت قبل التحصين (مأخوذة من نتيجة audit.sql)
-- ⚠️ لا تشغّله على القاعدة الحالية — هذا للتوثيق ولبيئة الاختبار فقط.
-- الترتيب: 000 → 002 → 003 → 004 ...
-- (أسماء أنواع sub/payment/payer الحقيقية غير معروفة؛ الكود ما يعتمد عليها)
-- ============================================================

create type public.app_role as enum ('rep', 'acc', 'mgr', 'wh', 'admin');
create type public.inv_stage as enum ('new', 'acc', 'decision', 'done', 'cancel');
create type public.inv_sub as enum ('mgr', 'cust', 'wh');
create type public.pay_method as enum ('cash', 'credit', 'cheque', 'transfer');
create type public.transport_payer as enum ('none', 'company', 'customer');

create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  full_name text default '',
  role public.app_role default 'rep',
  active boolean default false,
  created_at timestamptz default now()
);

create table public.invoices (
  id bigint generated by default as identity (start with 1000) primary key,
  customer text default '',
  quote_no text default '',
  res_no text default '',
  rep_id uuid references public.profiles (id),
  value numeric default 0,
  pdf_path text,
  pdf_name text,
  pdf_size integer,
  stage public.inv_stage default 'new',
  sub public.inv_sub,
  payment public.pay_method,
  credit_days integer,
  payer public.transport_payer,
  transport_amt numeric default 0,
  unload_amt numeric default 0,
  ld boolean default false,
  ld_pct numeric,
  ld_due date,
  from_purch boolean default false,
  exc boolean default false,
  exc_reason text default '',
  notes text default '',
  sales_no text default '',
  cancel_reason text default '',
  returned integer default 0,
  created_by uuid default auth.uid(),
  created_at timestamptz default now(),
  stage_at timestamptz default now(),
  closed_at timestamptz
);

create table public.invoice_log (
  id bigint generated by default as identity primary key,
  invoice_id bigint references public.invoices (id) on delete cascade,
  actor uuid,
  body text,
  at timestamptz default now()
);

create table public.invoice_comments (
  id bigint generated by default as identity primary key,
  invoice_id bigint references public.invoices (id) on delete cascade,
  author uuid default auth.uid(),
  body text,
  is_system boolean default false,
  at timestamptz default now()
);

alter table public.profiles enable row level security;
alter table public.invoices enable row level security;
alter table public.invoice_log enable row level security;
alter table public.invoice_comments enable row level security;

-- ---------- دوال مساعدة ----------
create function public.my_role() returns public.app_role
language sql stable security definer set search_path = public as
$$ select role from public.profiles where id = auth.uid() and active $$;

create function public.is_admin() returns boolean
language sql stable security definer set search_path = public as
$$ select public.my_role() = 'admin' $$;

create function public.is_active() returns boolean
language sql stable security definer set search_path = public as
$$ select exists (select 1 from public.profiles where id = auth.uid() and active) $$;

create function public.add_log(p_inv bigint, p_body text) returns void
language sql security definer set search_path = public as
$$ insert into public.invoice_log (invoice_id, actor, body) values (p_inv, auth.uid(), p_body) $$;

create function public.ld_amount(public.invoices) returns numeric
language sql stable as
$$ select case when $1.ld then round($1.value * coalesce($1.ld_pct,0) / 100, 2) else 0 end $$;

create function public.handle_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, full_name, role, active)
  values (new.id, coalesce(new.raw_user_meta_data->>'full_name',''), 'rep', false)
  on conflict (id) do nothing;
  return new;
end $$;
create trigger on_auth_user_created after insert on auth.users
  for each row execute function public.handle_new_user();

create function public.invoices_guard() returns trigger
language plpgsql security definer set search_path = public as $$
declare r public.app_role := public.my_role();
begin
  if r = 'admin' then return new; end if;
  if r = 'rep' then
    if (new.payment, new.credit_days, new.payer, new.transport_amt, new.unload_amt,
        new.ld, new.ld_pct, new.ld_due, new.from_purch, new.exc, new.exc_reason)
       is distinct from
       (old.payment, old.credit_days, old.payer, old.transport_amt, old.unload_amt,
        old.ld, old.ld_pct, old.ld_due, old.from_purch, old.exc, old.exc_reason)
    then raise exception 'المندوب ما يكدر يعدل الشروط';
    end if;
  end if;
  if r = 'acc' then
    if (new.customer, new.quote_no, new.res_no, new.value, new.rep_id, new.pdf_path)
       is distinct from
       (old.customer, old.quote_no, old.res_no, old.value, old.rep_id, old.pdf_path)
    then raise exception 'المحاسب ما يكدر يعدل بيانات الطلب الأساسية';
    end if;
  end if;
  return new;
end $$;
create trigger invoices_guard_trg before update on public.invoices
  for each row execute function public.invoices_guard();

-- ---------- دوال الإجراءات (النسخة الأصلية — بيها ثغرة NULL، تنصلح بـ 002) ----------
create function public.inv_send_to_acc(p_id bigint) returns public.invoices
language plpgsql security definer set search_path = public as $$
declare v public.invoices; r public.app_role := public.my_role();
begin
  select * into v from public.invoices where id = p_id for update;
  if v is null then raise exception 'الطلب غير موجود'; end if;
  if v.stage <> 'new' then raise exception 'الطلب مو بمرحلة طلب جديد'; end if;
  if not (r = 'admin' or (r = 'rep' and v.rep_id = auth.uid())) then raise exception 'ما عندك صلاحية'; end if;
  if btrim(v.customer) = '' then raise exception 'اسم الزبون مطلوب'; end if;
  if btrim(v.quote_no) = '' and btrim(v.res_no) = '' then raise exception 'رقم عرض السعر أو رقم الحجز مطلوب'; end if;
  if v.value <= 0 then raise exception 'قيمة الفاتورة مطلوبة'; end if;
  if v.pdf_path is null then raise exception 'ملف الـ PDF مطلوب'; end if;
  update public.invoices set stage='acc', sub=null, stage_at=now() where id=p_id returning * into v;
  perform public.add_log(p_id, 'أرسل الطلب للحسابات');
  return v;
end $$;

create function public.inv_send_to_decision(p_id bigint) returns public.invoices
language plpgsql security definer set search_path = public as $$
declare v public.invoices; r public.app_role := public.my_role();
begin
  select * into v from public.invoices where id = p_id for update;
  if v is null then raise exception 'الطلب غير موجود'; end if;
  if v.stage <> 'acc' then raise exception 'الطلب مو بمرحلة الحسابات'; end if;
  if r not in ('acc','admin') then raise exception 'ما عندك صلاحية'; end if;
  if v.payment is null then raise exception 'طريقة السداد مطلوبة'; end if;
  update public.invoices set stage='decision', sub='mgr', stage_at=now() where id=p_id returning * into v;
  perform public.add_log(p_id, 'أرسل الطلب للقرار');
  return v;
end $$;

create function public.inv_approve(p_id bigint) returns public.invoices
language plpgsql security definer set search_path = public as $$
declare v public.invoices; r public.app_role := public.my_role();
begin
  select * into v from public.invoices where id = p_id for update;
  if v.stage <> 'decision' or v.sub <> 'mgr' then raise exception 'الطلب مو بانتظار موافقة المدير'; end if;
  if r not in ('mgr','admin') then raise exception 'الموافقة للمدير فقط'; end if;
  update public.invoices set sub='cust', stage_at=now() where id=p_id returning * into v;
  perform public.add_log(p_id, 'وافق المدير على الشروط');
  return v;
end $$;

create function public.inv_return_to_acc(p_id bigint, p_reason text) returns public.invoices
language plpgsql security definer set search_path = public as $$
declare v public.invoices; r public.app_role := public.my_role();
begin
  select * into v from public.invoices where id = p_id for update;
  if v.stage <> 'decision' or v.sub <> 'mgr' then raise exception 'الطلب مو بانتظار موافقة المدير'; end if;
  if r not in ('mgr','admin') then raise exception 'الإرجاع للمدير فقط'; end if;
  update public.invoices set stage='acc', sub=null, stage_at=now(), returned = returned + 1 where id=p_id returning * into v;
  insert into public.invoice_comments (invoice_id, body, is_system) values (p_id, 'إرجاع للحسابات: ' || p_reason, true);
  perform public.add_log(p_id, 'أرجع الطلب للحسابات');
  return v;
end $$;

create function public.inv_customer_accept(p_id bigint) returns public.invoices
language plpgsql security definer set search_path = public as $$
declare v public.invoices; r public.app_role := public.my_role();
begin
  select * into v from public.invoices where id = p_id for update;
  if v.stage <> 'decision' or v.sub <> 'cust' then raise exception 'الطلب مو بانتظار رد الزبون'; end if;
  if not (r in ('mgr','admin') or (r='rep' and v.rep_id = auth.uid())) then raise exception 'ما عندك صلاحية'; end if;
  update public.invoices set sub='wh', stage_at=now() where id=p_id returning * into v;
  perform public.add_log(p_id, 'أكد موافقة الزبون');
  return v;
end $$;

create function public.inv_customer_refuse(p_id bigint, p_reason text) returns public.invoices
language plpgsql security definer set search_path = public as $$
declare v public.invoices; r public.app_role := public.my_role();
begin
  select * into v from public.invoices where id = p_id for update;
  if v.stage <> 'decision' or v.sub <> 'cust' then raise exception 'الطلب مو بانتظار رد الزبون'; end if;
  if not (r in ('mgr','admin') or (r='rep' and v.rep_id = auth.uid())) then raise exception 'ما عندك صلاحية'; end if;
  if btrim(coalesce(p_reason,'')) = '' then raise exception 'سبب الرفض مطلوب'; end if;
  update public.invoices set stage='cancel', sub=null, cancel_reason=p_reason, stage_at=now(), closed_at=now() where id=p_id returning * into v;
  perform public.add_log(p_id, 'سجل رفض الزبون وألغى الطلب');
  return v;
end $$;

create function public.inv_complete(p_id bigint, p_sales_no text) returns public.invoices
language plpgsql security definer set search_path = public as $$
declare v public.invoices; r public.app_role := public.my_role();
begin
  select * into v from public.invoices where id = p_id for update;
  if v.stage <> 'decision' or v.sub <> 'wh' then raise exception 'الطلب مو بانتظار المخزن'; end if;
  if r not in ('wh','mgr','admin') then raise exception 'التحويل للمخزن أو المدير'; end if;
  if btrim(coalesce(p_sales_no,'')) = '' then raise exception 'رقم المبيعات مطلوب'; end if;
  update public.invoices set stage='done', sub=null, sales_no=p_sales_no, stage_at=now(), closed_at=now() where id=p_id returning * into v;
  perform public.add_log(p_id, 'حول الطلب لمبيعات برقم ' || p_sales_no);
  return v;
end $$;

-- ---------- السياسات ----------
create policy comments_insert on public.invoice_comments for insert to authenticated
  with check (is_active() and author = auth.uid() and exists (select 1 from invoices i where i.id = invoice_comments.invoice_id));
create policy comments_read on public.invoice_comments for select to authenticated
  using (exists (select 1 from invoices i where i.id = invoice_comments.invoice_id));
create policy log_read on public.invoice_log for select to authenticated
  using (exists (select 1 from invoices i where i.id = invoice_log.invoice_id));

create policy invoices_delete on public.invoices for delete to authenticated
  using (is_admin() or (my_role() = 'rep' and rep_id = auth.uid() and stage = 'new'));
create policy invoices_insert on public.invoices for insert to authenticated
  with check (stage = 'new' and (is_admin() or (my_role() = 'rep' and rep_id = auth.uid())));
create policy invoices_read on public.invoices for select to authenticated
  using (case my_role()
    when 'admin' then true when 'mgr' then true when 'acc' then true
    when 'wh' then stage = any (array['decision'::inv_stage, 'done'::inv_stage])
    when 'rep' then rep_id = auth.uid()
    else false end);
create policy invoices_update on public.invoices for update to authenticated
  using (is_admin() or (my_role() = 'rep' and rep_id = auth.uid() and stage = 'new') or (my_role() = 'acc' and stage = 'acc'))
  with check (is_admin() or (my_role() = 'rep' and rep_id = auth.uid() and stage = 'new') or (my_role() = 'acc' and stage = 'acc'));

create policy profiles_admin_ins on public.profiles for insert to authenticated with check (is_admin());
create policy profiles_admin_upd on public.profiles for update to authenticated using (is_admin()) with check (is_admin());
create policy profiles_read on public.profiles for select to authenticated using (is_active() or id = auth.uid());

create policy inv_files_delete on storage.objects for delete to authenticated
  using (bucket_id = 'invoices' and is_admin());
create policy inv_files_read on storage.objects for select to authenticated
  using (bucket_id = 'invoices' and is_active());
create policy inv_files_upload on storage.objects for insert to authenticated
  with check (bucket_id = 'invoices' and is_active());

-- ---------- الصلاحيات (مطابقة لنتيجة الفحص) ----------
grant select, insert, delete on public.invoices to authenticated;
grant update (customer, quote_no, res_no, rep_id, value, pdf_path, pdf_name, pdf_size,
              payment, credit_days, payer, transport_amt, unload_amt, ld, ld_pct, ld_due,
              from_purch, exc, exc_reason, notes) on public.invoices to authenticated;
grant select, insert, update on public.profiles to authenticated;
grant select on public.invoice_log to authenticated;
grant select, insert on public.invoice_comments to authenticated;
grant truncate, trigger, references on public.invoices, public.profiles, public.invoice_log, public.invoice_comments to anon, authenticated;

insert into storage.buckets (id, public, file_size_limit, allowed_mime_types)
values ('invoices', false, 2097152, array['application/pdf']);
